name: Build ZMK firmware
on:
    pull_request:
    workflow_dispatch:
    push:
        paths:
        - 'build.yaml'
        - 'config/**'
        - 'boards/**'




jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
