name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zmk-config
    steps:
      - name: Run ZMK build workflow
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
